version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: freelancer-server
    volumes:
      - ./server:/usr/src/server
      - /usr/src/server/node_modules
    ports:
      - "4000:4000"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: freelancer-client
    volumes:
      - ./client:/usr/src/client
      - /usr/src/client/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"

networks:
  default:
    driver: bridge
