version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    environment:
      - NODE_ENV=development
    image: freelancer-client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - '3000:3000'
  mongo:
    image: mongo:5.0.10
    ports:
      - '27017:27017'
    volumes:
      - data-volume:/data/db
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - PORT=3001
    image: freelancer-server
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - '3001:3001'

networks:
  default:
    driver: bridge

volumes:
  data-volume:
    driver: local
